name: Run pytest

on:
  push:
    branches: [ * ]
  pull_request:
    branches: [ * ]

jobs:
  pytest:
    name: Build and publish Python distribution
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Initialize Python 3.10.1
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/test.txt
      - name: run pytest
        run: pytest
